### ISSUE TITLE
Travis CI passes check it shouldn't

### ISSUE THREAD

**Issue by pltrz** [void-linux/void-docs#81] opened 2019-03-04 23:44 UTC
I've described an issue I encountered at bobertlo/vmd/issues/7. In the meantime, this issue resulted in a [successful travis check](https://travis-ci.org/void-linux/void-docs/builds/501751217) even though it should not return 0.

**Comment by bobertlo** [comment] 2019-03-05 00:25
I am cleaning my house, but will look at this when I get back. I set it up to not support html tags for now. Are these coming from inside codeblocks? This is a strage bug, because the codeblock contents should only be raw content. I'll look at what blackfriday is giving us to work with. If it actually changed any contents, it would fail the CI, so this is very odd.

BlackFriday has some bugs and seems to only be tested for HTML rendering. Still, very odd...

**Comment by bobertlo** [comment] 2019-03-05 01:23
So, with more details in #76, upstream is broken on this one, and I'm not writing a whole markdown parser. 

Perhaps it was hubris for us to reach towards code-blocks inside of block-quotes?

I'm digging around, but in my past experience with blackfriday, this is not going to get fixed anytime soon upstream, but I'm already vendoring another bugfix in the vmd repo.

Stylistically I'm leaning towards less use of blockquotes anyways. They read/look a lot better on a wiki than in a manual. So, probably avoid them for now and don't hold your breath on this feature.

**Comment by pltrz** [comment] 2019-03-05 22:17
> Stylistically I'm leaning towards less use of blockquotes anyways. They read/look a lot better on a wiki than in a manual.

I'm afraid I disagree here; I believe blockquotes can be effective in mentioning bits of information that are tangentially related to the topic on hand. For example, things that are worthwhile knowing, but if included in the main body would break the flow of related information and excluding altogether would render the page lacking.

**Comment by bobertlo** [comment] 2019-03-05 22:51
I will look into it. I’m frustrated that this issue did not come up until it’s been running for so long. I can’t reproduce it outside of your file and have not been able to change your file in any way to make it go away. I’m fearing some sort of complex interaction inside the parser, but it’s not my code. I will try to come up with a fix as soon as I have more time.

**Comment by pltrz** [comment] 2019-03-05 23:01
> I can’t reproduce it outside of your file and have not been able to change your file in any way to make it go away.

Yes, I was getting seriously weirded out by it. It's hard to try and isolate the cause since it's so inconsistent.

**Comment by bobertlo** [comment] 2019-03-06 21:48
I took a look into blackfriday and I didn't quite wrap my head around it, but that code isn't as scary as I thought it would be. I'll put this near the top of my list.

**Comment by bobertlo** [comment] 2019-03-07 16:10
I'm closing this. There might be a better solution, but I'm adding your special page to the tests so this will be covered.

**Closed by bobertlo** 2019-03-07 16:10 UTC
Labels: bug
