### ISSUE TITLE
Troubleshooting common xbps errors section is only a stub

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-docs#89] opened 2019-03-29 02:09 UTC
Good topics to cover:

* diagnosing broken shlibs issues
* verifying that the repositories are configured correctly

**Comment by ericonr** [comment] 2020-05-17 04:19
@CameronNemo what do you mean by checking if repos are configured? I know I can do `xbps-query -L`, but that's as far as I go.

**Comment by flexibeast** [comment] 2020-07-12 07:17
Asking about the second point on IRC, @nilium suggested:

> Presumably means verifying the xbps config points to the correct repositories for a user's system.

**Comment by ericonr** [comment] 2020-07-12 15:21
So basically point people to the repositories page so they can check the links? Also show an example of an error when arch repodata can't be found in the repository?

**Comment by flexibeast** [comment] 2020-07-13 05:33
Yeah, that was my thought. If i change `/usr/share/xbps.d/00-repository-main.conf` to refer to `current/musl` rather than `current`, then do `xbps-install -S`, i get:

    [*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-repodata' ...
    ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-repodata': Not Found

Is that particular error most likely to be caused by having the incorrect URL? If not, i can say that "incorrect URL" *might* be its cause.

**Comment by ericonr** [comment] 2020-07-13 05:44
I think with "Not Found" in the end it is. When it's something like DNS we get "Transient error...".

This reminds me, should we document the issues that can be caused by having the wrong system time?

**Comment by flexibeast** [comment] 2020-07-13 06:07
> should we document the issues that can be caused by having the wrong system time?

Definitely; i can include that in my PR. [This thread](https://old.reddit.com/r/voidlinux/comments/hizldf/void_linux_update_issue/) suggests it results in an "Operation not permitted" error, but i just tried adjusting my local clock to be off by 12 hours, and `xbps-install -S` worked just fine, so i can't confirm which error is actually produced.

**Comment by flexibeast** [comment] 2020-07-13 14:18
Closed by #400.

**Closed by flexibeast** 2020-07-13 14:18 UTC
Labels: enhancement
