### ISSUE TITLE
[Documentation improvement for the installation] Add how much RAM is needed for loading the image into RAM (e. g. if 2 GB is enough or not, what would be recommended)

### ISSUE THREAD

**Issue by rubyFeedback** [void-linux/void-docs#144] opened 2020-01-20 21:36 UTC
From https://docs.voidlinux.org/installation/live-images/guide.html:

"Boot your machine from the install media you created. If you have enough RAM, there is an option on the boot screen to load the entire image into ram, which will take some time but speed up the rest of the install process."

Could it be said how much RAM is needed? I have an old computer with only 2 gigabyte of RAM. Is it worth to load the entire image into RAM? Right now we as users don't know. A recommendation here would be nice.

**Comment by ericonr** [comment] 2020-04-13 20:48
So, booting the x86_64-musl live image with XFCE:

```
$ free -h
```

Memory: total 7.7Gi, used 201Mi, free 5.7Gi, shared 619Mi, buff/cache 1.2Gi, available 6.6Gi.

So it seems to be using at least 2Gi, and I'd need some extra to run xbps-install stuff (perhaps). Perhaps this image is too big to run from RAM in a system with only 2GB of RAM.

It is running from RAM completely, I have removed the pen drive (gotta say it's a funny feeling).

**Comment by ericonr** [comment] 2020-04-13 21:19
@bobertlo do you think this kind of information could fit somewhere? I can download all live versions of void, boot them and see what the memory requirements are. If we can define some standard for reporting this info, I can try to update the current requirements page (I think).

**Comment by bobertlo** [comment] 2020-04-14 03:49
So, the installation software is very light. I would imagine 2GB would be okay. 1GB would probably have issues. There are a couple small services running and xbps, then some other system commands.

To be honest, I'm not sure how helpful more detailed information would be would be. Most users should know in their heart if they have enough RAM or not.

Beyond that, I really don't think a comparison between ISOs is necessary since they are similar in size, more or less.

**Comment by ericonr** [comment] 2020-04-20 22:47
> Most users should know in their heart if they have enough RAM or not.

I agree.

https://docs.voidlinux.org/installation/base-requirements.html so, do you think anything here needs to be updated? Otherwise I believe we could close this issue. I can see the case for documenting the requirements for *just* the XFCE i686 image, as an aid for users with underpowered hardware and who aren't really savvy in an environment without a GUI. Not sure if that would fit inside the docs, though.

**Comment by bobertlo** [comment] 2020-04-21 02:24
I'm thinking we can close this too. The issue is regarding the RAM mechanism in the live images, not the installed system.

I'd be careful about what we document on the requirements for running systems (as far as maintainability) but some numbers would be good. I'm not sure where/when the current numbers listed came from.

**Closed** 2020-04-21 02:24 UTC
