### ISSUE TITLE
voidlinux.eu refs

### ISSUE THREAD

**Issue by xtraeme** [void-linux/void-docs#125] opened 2019-10-27 06:03 UTC
The official documentation still has refs to voidlinux.eu... please fix!

**Comment by nilium** [comment] 2019-10-27 07:13
Pretty sure the only reference to it is in the PGP key used to sign image checksums. Unless / until the key is changed, the docs are correct.

**Comment by nilium** [comment] 2019-10-27 07:21
As a follow-up, I'm assuming you're referring to this: https://github.com/void-linux/void-docs/blob/master/src/installation/live-images/downloading.md#verify-image-authenticity

If so, this should be an issue reading "the image signing key still uses a voidlinux.eu domain." We could probably file it under enhancements since it's not a bug (as you know, there was very little anyone could do about the voidlinux.eu domain expiring), but it'd probably need to be moved under the infrastructure repo.

If not, you're going to have to point out where, because I've already searched for references several different ways.

**Comment by bobertlo** [comment] 2019-10-27 15:17
I have to agree with @nilium here.

```
[robert@hades void-docs] (master)$ find . -type f | xargs grep voidlinux.eu
./src/installation/live-images/downloading.md:   <[images@voidlinux.eu](mailto:images@voidlinux.eu)>
./src/installation/live-images/downloading.md:gpg: key B48282A4: public key "Void Linux Image Signing Key <images@voidlinux.eu>" imported
./src/installation/live-images/downloading.md:gpg: Good signature from "Void Linux Image Signing Key <images@voidlinux.eu>"
```
This could possibly be reopened with infrastructure, but I don't think we should rewrite history. I am closing this here.

**Closed by bobertlo** 2019-10-27 15:17 UTC
