### ISSUE TITLE
Add guide on full disk encryption

### ISSUE THREAD

**Issue by fac3plant** [void-linux/void-docs#166] opened 2020-03-19 04:53 UTC
Please add a guide explaining how to do Full Disk Encryption. There is [This guide](https://wiki.voidlinux.org/Manual_Install_with_encrypted_boot) and [This guide](https://wiki.voidlinux.org/Full_Disk_Encryption_w/Encrypted_Boot). 

It would be nice to be able to explain some Void specific issues with doing this, and to have a recommended way to do Full Disk Encryption.

**Comment by Duncaen** [comment] 2020-03-19 12:34
Duplicate of https://github.com/void-linux/void-docs/issues/85.

**Closed by Duncaen** 2020-03-19 12:34 UTC
